apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  postgres_port: "{{ .Values.postgres.postgresql.port }}"
  postgres_host: "{{ .Values.postgres.postgresql.host }}"
  port: "{{ .Values.postgres.port }}"