apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  hostPath:
    path: {{ .Values.postgres.storage.hostPath }}