namespace: student-api
application:
  replicaCount: 1
  name: restapi
  port: 8002
  configname: postgres
  secretName: dev-db
  image:
    repository: venkateshtangaraj/studentapi
    tag: de2a96f21a4b301089e46e0f98f218fd87e57df2
  migration:
    image:
      repository: venkateshtangaraj/db_migration
      tag: v1.0.0
  service:
    type: NodePort
    port: 8080
    nodePort: 30007
  postgresql:
    host: postgres-svc
    port: 5432
  nodeSelector:
    type: application
