namespace: student-api
application:
  replicaCount: 1
  name: restapi
  port: 8002
  configname: postgres
  secretName: dev-db
  image:
    repository: venkateshtangaraj/studentapi
    tag: v1.0.1
  migration:
    image:
      repository: venkateshtangaraj/studentapi
      tag: v1.0.1
    pyway:
      type: postgres
      table: pyway_schema_history
      migrationDir: /app/migrations
    command:
      - "sh"
      - "-c"
    args:
      - "pyway migrate"
  service:
    type: NodePort
    port: 8080
    nodePort: 30007
  postgresql:
    host: postgres-svc
    port: 5432
  nodeSelector:
    type: application
