apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.application.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      {{- with .Values.application.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.application.name }}
        image: "{{ .Values.application.image.repository }}:v{{ .Values.application.image.tag }}"
        ports:
        - containerPort: {{ .Values.application.port }}
        envFrom:
        - secretRef:
            name: dev-db
        env:
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.application.configname }}-config
              key: postgres_port
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.application.configname }}-config
              key: postgres_host
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.application.configname }}-config
              key: port
      initContainers:
      - name: migration
        image: "{{ .Values.application.migration.image.repository }}:v{{ .Values.application.migration.image.tag }}"
        env:
        - name: PYWAY_TYPE
          value: "{{ .Values.application.migration.pyway.type }}"
        - name: PYWAY_TABLE
          value: "{{ .Values.application.migration.pyway.table }}"
        - name: PYWAY_DATABASE_MIGRATION_DIR
          value: "{{ .Values.application.migration.pyway.migrationDir }}"
        - name: PYWAY_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.application.configname }}-config
              key: postgres_host
        - name: PYWAY_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.application.configname }}-config
              key: postgres_port
        - name: PYWAY_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.application.secretName }}
              key: POSTGRES_DB
        - name: PYWAY_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.application.secretName }}
              key: POSTGRES_USER
        - name: PYWAY_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.application.secretName }}
              key: POSTGRES_PASSWORD
        command: {{ .Values.application.migration.command | toJson }}
        args: {{ .Values.application.migration.args | toJson }}
